Increase INWX propagation timeout to 360s to improve robustness
go-acme/lego pull request #1314
Opened 2020-12-06 09:22 UTC by dragetd

INWX has rather unstable propagation delays. Users reported that the
robustness of the DNS challenge improves with a longer timeout, thus instead
of using the default, hardcode a larger default. Six minutes seems to work
fine so far.

Fixes #1297

2020-12-06 09:23 UTC, dragetd commented
I was not sure if you want a note in the documentation that the timeout is larger than usual. Tell me if I should change it. :-)

2020-12-09 20:47 UTC, ldez requested changes
Hello, as your PR comes from a GitHub organization, I'm not able to commit on it.

So could you run `make generate-dns` and commit the result and rebase your PR.

Using a GitHub organization to handle forks is something that can be an issue with bots/automation, I can understand your approach but you have to know the constraints and that can cause problems to open source projects.

2020-12-09 20:47 UTC, ldez commented on providers/dns/inwx/inwx.go
> +		PropagationTimeout: env.GetOrDefaultSecond(EnvPropagationTimeout, 360),
```suggestion
		PropagationTimeout: env.GetOrDefaultSecond(EnvPropagationTimeout, 360*time.Second),
```

2020-12-14 07:16 UTC, dragetd commented
Uh, I did not know this! How annoying! x.x Well, they added repository-typo filters and by default no longer show forks, it did improve ever since I made this construct. I guess it is time to clean it up!

Sorry for the hassle. :-(

I included your change and the updated documentation, rebased and squashed the changes.

2020-12-14 08:18 UTC, ldez approved these changes
Thanks :+1:

2020-12-14 08:19 UTC, ldez requested changes
Could you run format the source code (gofmt) ? thank you

2020-12-14 21:56 UTC, ldez approved these changes

2020-12-14 21:57 UTC, merged

2020-12-15 06:57 UTC, dragetd commented
I am sorry for all the hassle :( and I am also nuking my organizations now!