Several improvements to the PowerDNS provider
go-acme/lego pull request #1374
Opened 2021-03-12 15:07 UTC by pieterlexis

Hi folks,

This PR has several improvements to the PowerDNS DNS Provider.

### Server name
The PowerDNS API allows for a `server_name` other than 'localhost'. The auth server itself does not use it, but proxies that have multiple backends can. We are running such a proxy. The first commit in this series adds the `PDNS_SERVER_NAME` option to set this. The default remains the same.

### content-type in PATCH requests
Some proxies require the Content-Type header to be set. The second commit sets this header to 'application/json' when the method is not DELETE or GET.

### 'records' can be omitted in rrset
The API allows the 'records' field to be omitted in the request when the `changetype` is 'DELETE'. The third commit implements this omission.

### Error reporting
I was confused by an error report that had the word 'fetch' hardcoded. The last commit changes this to the HTTP Method used.

If there is anything you need more in this PR, let me know.

Cheers,

Pieter Lexis
PowerDNS

2021-03-12 15:18 UTC, pieterlexis commented
Failures seem unrelated to the changed code:

```
=== RUN   TestFindPrimayNsByFqdnCustom/no_nameservers
--- FAIL: TestFindPrimayNsByFqdnCustom (10.54s)
    --- PASS: TestFindPrimayNsByFqdnCustom/domain_is_a_CNAME (0.01s)
    --- PASS: TestFindPrimayNsByFqdnCustom/domain_is_a_non-existent_subdomain (0.09s)
    --- PASS: TestFindPrimayNsByFqdnCustom/domain_is_a_eTLD (0.12s)
    --- PASS: TestFindPrimayNsByFqdnCustom/domain_is_a_cross-zone_CNAME (0.00s)
    --- FAIL: TestFindPrimayNsByFqdnCustom/NXDOMAIN (10.15s)
    --- PASS: TestFindPrimayNsByFqdnCustom/several_non_existent_nameservers (0.16s)
```

2021-03-16 23:13 UTC, dmke approved these changes
LGTM. Any objections, @ldez?

2021-03-16 23:26 UTC, ldez requested changes
@pieterlexis could run `make generate-dns`

2021-03-16 23:47 UTC, dmke commented
Ah yes, of course.

2021-03-17 06:56 UTC, pieterlexis commented
> @pieterlexis could run `make generate-dns`

Done, committed and rebased!

2021-03-17 08:53 UTC, ldez approved these changes
Thanks :+1:

2021-03-17 08:53 UTC, merged