feat: add tencent cloud as new DNS provider
go-acme/lego pull request #1527
Opened 2021-11-09 05:16 UTC by baranwang

2021-11-09 05:18 UTC, ldez commented
Hello, in order for a PR adding a DNS provider to be accepted, you have to:

- [ ] add a description to your PR
- [ ] be able to maintain this provider
- [ ] have a homogeneous design with the other providers
- [ ] add tests (units)
```shell
make test
```
- [ ] add tests ("live")
https://github.com/go-acme/lego/blob/c938de68f262c057542d44bcb67ef961cefcc60e/providers/dns/cloudflare/cloudflare_test.go#L125-L151

```shell
make test
```
- [ ] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [ ] generate CLI help, documentation, and readme.
```bash
make generate-dns
```
- [ ] be able to do: _(and put the output of this command to a comment in your PR)_
```bash
rm -rf .lego

./lego -m your@email.com --dns YOUR_PROVIDER_NAME -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```
Note the wildcard domain is important.
- [ ] pass the linter ([golangci-lint](https://github.com/golangci/golangci-lint#install) must be installed):
```shell
make checks
```
- [ ] do `go mod tidy`

2021-11-09 07:02 UTC, baranwang commented
```
go run cmd/lego/main.go -m your@email.com --dns tencentcloud -d test.neobaran.com -s https://acme-staging-v02.api.letsencrypt.org/directory run      
2021/11/09 15:00:12 [INFO] [test.neobaran.com] acme: Obtaining bundled SAN certificate
2021/11/09 15:00:13 [INFO] [test.neobaran.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/894627238
2021/11/09 15:00:13 [INFO] [test.neobaran.com] acme: Could not find solver for: tls-alpn-01
2021/11/09 15:00:13 [INFO] [test.neobaran.com] acme: Could not find solver for: http-01
2021/11/09 15:00:13 [INFO] [test.neobaran.com] acme: use dns-01 solver
2021/11/09 15:00:13 [INFO] [test.neobaran.com] acme: Preparing to solve DNS-01
2021/11/09 15:00:13 [INFO] [test.neobaran.com] acme: Trying to solve DNS-01
2021/11/09 15:00:13 [INFO] [test.neobaran.com] acme: Checking DNS record propagation using [198.18.0.2:53]
2021/11/09 15:00:15 [INFO] Wait for propagation [timeout: 10m0s, interval: 2s]
2021/11/09 15:00:15 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:17 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:19 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:21 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:23 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:25 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:27 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:29 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:31 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:33 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:35 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:37 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:39 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:41 [INFO] [test.neobaran.com] acme: Waiting for DNS record propagation.
2021/11/09 15:00:51 [INFO] [test.neobaran.com] The server validated our request
2021/11/09 15:00:51 [INFO] [test.neobaran.com] acme: Cleaning DNS-01 challenge
2021/11/09 15:00:51 [INFO] [test.neobaran.com] acme: Validations succeeded; requesting certificates
2021/11/09 15:00:57 [INFO] [test.neobaran.com] Server responded with a certificate.
```

2021-11-10 03:47 UTC, baranwang commented
i try master branch, some error, so i think the unit test can not passed not my request's problem.

2021-11-10 08:33 UTC, ldez commented
The failures come from the tests of your provider, so it's a problem with your PR.

2021-11-10 08:37 UTC, ldez requested changes

2021-11-10 08:37 UTC, ldez commented on providers/dns/tencentcloud/tencentcloud_test.go
> +		},
```suggestion
```

2021-11-10 08:37 UTC, ldez commented on providers/dns/tencentcloud/tencentcloud.toml
> +Since = "v4.5.4"
```suggestion
Since = "v4.6.0"
```

2021-11-10 08:37 UTC, ldez commented on providers/dns/tencentcloud/tencentcloud.toml
> +GoClient = "https://github.com/tencentcloud/tencentcloud-sdk-go"
```suggestion
[Configuration]
  [Configuration.Credentials]
    TENCENTCLOUD_SECRET_ID = "Access key ID"
    TENCENTCLOUD_SECRET_KEY = "Access Key secret"
  [Configuration.Additional]
    TENCENTCLOUD_POLLING_INTERVAL = "Time between DNS propagation check"
    TENCENTCLOUD_PROPAGATION_TIMEOUT = "Maximum waiting time for DNS propagation"
    TENCENTCLOUD_TTL = "The TTL of the TXT record used for the DNS challenge"
    TENCENTCLOUD_HTTP_TIMEOUT = "API request timeout"

[Links]
  API = "https://cloud.tencent.com/document/product/1427/56153"
  GoClient = "https://github.com/tencentcloud/tencentcloud-sdk-go"
```

2021-11-10 08:37 UTC, ldez commented on providers/dns/tencentcloud/tencentcloud.go
> +
```suggestion

	if config.SecretID == "" || config.SecretKey == "" {
		return nil, errors.New("tencentcloud: credentials missing")
	}

```

2021-11-14 15:26 UTC, ldez commented
Hello,

could you reopen the PR with a personal fork?
GitHub doesn't allow to change/edit of the content of a PR from an organization.

2021-11-19 21:55 UTC, ldez commented
ping @baranwang

2021-12-03 15:09 UTC, ldez commented
ping @baranwang

2021-12-07 17:25 UTC, ldez commented
last call @baranwang

2021-12-09 07:30 UTC, baranwang commented
@ldez sorry, I'm busy at work recently, didn't see it.

2021-12-14 17:06 UTC, ldez commented
https://github.com/go-acme/lego/pull/1527#issuecomment-968312246

2021-12-15 04:40 UTC, baranwang commented
> [#1527 (comment)](https://github.com/go-acme/lego/pull/1527#issuecomment-968312246)

I have transferred the warehouse to my personal account

2021-12-22 15:51 UTC, ldez approved these changes
Thanks

2021-12-22 15:58 UTC, merged

2022-02-11 04:31 UTC, libla commented
I use this providers but throw error:
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"invoke function failed with err: {\"Message\":\"error: one or more domains had a problem:\\n[*.honghuangyouxi.com] [*.honghuangyouxi.com] acme: error presenting token: tencentcloud: create record failed: [TencentCloudSDKError] Code=InvalidParameter.DomainInvalid, Message=域名不正确，请输入主域名，如 dnspod.cn。, RequestId=402891c3-cfff-45c0-9248-bfe006aab0bf\\n[honghuangyouxi.com] [honghuangyouxi.com] acme: error presenting token: tencentcloud: create record failed: [TencentCloudSDKError] Code=InvalidParameter.DomainInvalid, Message=域名不正确，请输入主域名，如 dnspod.cn。, RequestId=74f28883-f037-4a90-876f-1e1da90cc6a6\\n\",\"Type\":\"obtainError\",\"StackTrace\":null,\"ShouldExit\":false}","statusCode":430}

Is it because of the wildcard domain?

2022-02-11 04:33 UTC, ldez commented
ping @baranwang

2022-04-03 13:40 UTC, charlie0129 commented
> I use this providers but throw error:
> 
> ```
> {"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"invoke function failed with err: {\"Message\":\"error: one or more domains had a problem:\\n[*.honghuangyouxi.com] [*.honghuangyouxi.com] acme: error presenting token: tencentcloud: create record failed: [TencentCloudSDKError] Code=InvalidParameter.DomainInvalid, Message=域名不正确，请输入主域名，如 dnspod.cn。, RequestId=402891c3-cfff-45c0-9248-bfe006aab0bf\\n[honghuangyouxi.com] [honghuangyouxi.com] acme: error presenting token: tencentcloud: create record failed: [TencentCloudSDKError] Code=InvalidParameter.DomainInvalid, Message=域名不正确，请输入主域名，如 dnspod.cn。, RequestId=74f28883-f037-4a90-876f-1e1da90cc6a6\\n\",\"Type\":\"obtainError\",\"StackTrace\":null,\"ShouldExit\":false}","statusCode":430}
> ```
> 
> Is it because of the wildcard domain?

I ran into this issue too. There is something wrong in the implementation, i.e. the trailing dot in `domainData.domain` is causing problems. I will (probably) provide a fix.