pdns: fix usage of notify only when zone kind is Master or Slave (#1780)
go-acme/lego pull request #1781
Opened 2022-12-07 12:28 UTC by melck

Hello,

It should fix linked issue. What do you think about it ?

2023-01-07 18:13 UTC, dmke requested changes
Looks good, but could be slightly improved.

The conditional got complex enough to be extracted into a helper. This allows us (or maybe you?) to add a simple test case for it.

2023-01-07 18:13 UTC, dmke commented on providers/dns/pdns/pdns.go
> +	if d.apiVersion < 1 || (zone.Kind != "Master" && zone.Kind != "Slave") {
Can you extract the logic into a helper function, and invert the logic here?

Something like

```go
if supportsZonetransfer(d.apiVersion, zone.Kind) {
   	err = d.notify(zone.URL)
	if err != nil {
		return fmt.Errorf("pdns: %w", err)
	}
}
return nil
```

2023-01-07 18:13 UTC, dmke commented on providers/dns/pdns/pdns.go
> +	if d.apiVersion < 1 || (zone.Kind != "Master" && zone.Kind != "Slave") {
Same here.

2023-01-08 13:59 UTC, ldez approved these changes
LGTM

2023-01-08 14:01 UTC, dmke approved these changes

2023-01-08 14:12 UTC, merged