Add DNS provider for Nodion
go-acme/lego pull request #1844
Opened 2023-02-20 20:58 UTC by ldez

- [x] have a homogeneous design with the other providers
- [x] pass the linter
- [x] do `go mod tidy`
- [x] add tests (units)
- [x] add tests ("live")
- [x] add a [provider descriptor](https://github.com/go-acme/lego/blob/master/providers/dns/cloudflare/cloudflare.toml)
- [x] generate CLI help, documentation, and readme.
- [ ] be able to do: (and put the output of this command to a comment)
```bash
rm -rf .lego/

NODION_API_TOKEN="xxx" \
./lego -m lego@example.com --dns nodion -d *.example.com -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
```

Note the wildcard domain is important.

Closes #1661

2023-02-20 21:54 UTC, nik736 commented
I tested it locally as well and it's working perfect. Thanks :)

2023-02-22 18:50 UTC, dmke requested changes
LGTM, apart from the `go.mod` dependency.

2023-02-22 18:50 UTC, dmke commented on go.mod
> +require github.com/nrdcg/nodion v0.1.0
This looks out of place. Doesn't `go mod tidy` separate the dependencies in two groups (direct and indirect dependencies) anymore?

2023-02-22 19:05 UTC, dmke approved these changes

2023-02-27 00:11 UTC, merged