chore: replace GetRecord by GetChallengeInfo
go-acme/lego pull request #1863
Opened 2023-03-03 11:28 UTC by ldez

The name of the function `GetRecord` was ambiguous because it didn't return a record, but just information about the challenge (FQDN and token value).

I also do that because of the bug with the `acme-dns` provider: #1861

The provider `acme-dns` must not follow CNAME because the CNAME is handled internally by the provider.

2023-03-03 11:34 UTC, dmke reviewed
It'll take me some time to go through the changes, as I am a bit busy at the moment. I'll probably find some time tomorrow, though.

2023-03-06 19:21 UTC, dmke requested changes
Code changes LGTM. I've left some remarks for the documentation.

2023-03-06 20:35 UTC, ldez commented on docs/content/usage/library/Writing-a-Challenge-Solver.md
> +- `Value` is the record's value to set on the record.
I will revert this suggestion because the guide is about new providers.
I keep your text for the changelog of the next release.

2023-03-06 20:42 UTC, ldez commented
@dmke prepare your body my next PR will be a special :smile_cat:

2023-03-07 06:33 UTC, dmke commented on docs/content/usage/library/Writing-a-Challenge-Solver.md
> +- `Value` is the record's value to set on the record.
That's fine with me.

2023-03-07 06:35 UTC, dmke approved these changes

2023-03-07 08:39 UTC, merged