Add DNS provider for
go-acme/lego pull request #2332
Opened 2024-11-09 23:19 UTC by ldez

- [x] adds a description to your PR
- [x] have a homogeneous design with the other providers
- [x] add tests (units)
- [x] add tests ("live")
- [x] add a provider descriptor
- [x] generate CLI help, documentation, and readme.
- [ ] be able to do: _(and put the output of this command to a comment)_
  ```bash
  make build
  rm -rf .lego

  TECHNITIUM_SERVER_BASE_URL="http://localhost:5380" \
  TECHNITIUM_API_TOKEN="xxxxxxxxxxxxxxxxxxxxx" \
  ./dist/lego --email you@example.com --dns technitium -d '*.example.com' -d example.com -s https://acme-staging-v02.api.letsencrypt.org/directory run
  ```
  Note the wildcard domain is important.
- [x] pass the linter
- [x] do `go mod tidy`

Ping @abdeldjalil-fellah, can you run the command (with your domain, email, credentials, etc.)?

Closes #https://github.com/go-acme/lego/discussions/2331

https://github.com/go-acme/lego/discussions/2331#discussioncomment-11199643

2024-11-09 23:26 UTC, ldez commented
Maybe @ShreyasZare will want to try the PR.

2024-11-10 16:04 UTC, dmke requested changes
Just a small typo, otherwise LGTM

2024-11-10 16:04 UTC, dmke commented on providers/dns/technitium/technitium.toml
> +Technitium recommends to use in production over the HTTP API.
```suggestion
Technitium recommends to use it in production over the HTTP API.
```

2024-11-10 16:16 UTC, dmke approved these changes

2024-11-10 16:27 UTC, merged